# your name
title: Rouslan Zenetl

# install jekyll-tidy by running
# $ sudo gem install jekyll-tidy
gems:
  - rouge
  - jekyll-tidy
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag  # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-avatar

kramdown:
  auto_ids: false
  syntax_highlighter_opts:
    block:
      default_lang: javascript
      line_numbers: true
    span:
      line_numbers: false

jekyll_tidy:
  compress_html: false

sass:
  sass_dir: _sass
