# your name
title: Rouslan Zenetl

# install jekyll-tidy by running
# $ sudo gem install jekyll-tidy
gems: [jekyll-tidy,rouge]

kramdown:
  auto_ids: false
  syntax_highlighter_opts:
    block:
      default_lang: javascript
      line_numbers: true
    span:
      line_numbers: false

jekyll_tidy:
  compress_html: false

sass:
  sass_dir: _sass
