# your name
title: Rouslan Zenetl

# install jekyll-tidy by running
# $ sudo gem install jekyll-tidy
gems: [jekyll-tidy]

# config for jekyll-tidy
jekyll_tidy:
  # exclude: ["index.html"]
  compress_html: false
  # ignore_env: development